### ISSUE TITLE
make it header only, will you ?

### ISSUE THREAD

**Issue by jiabinruan** [jimmiebergmann/mini-yaml#1]

**Comment by paleozogt** [comment]
This project bills itself as a

> "Single header YAML 1.0 C++11 serializer/deserializer"

Furthermore, it says

> Put /yaml in your project directory and simply #include "yaml/Yaml.hpp".

However, it is *not* a single-header library.

For example, consider this `main.cpp`:
```
#include "yaml/Yaml.hpp"

int main() {
    Yaml::Node node;
    return 0;
}
```

Building this leads to link errors:
```
g++ -std=c++11 -Imini-yaml main.cpp                        
/tmp/cc5YtxZB.o: In function `main':
main.cpp:(.text+0x20): undefined reference to `Yaml::Node::Node()'
main.cpp:(.text+0x31): undefined reference to `Yaml::Node::~Node()'
collect2: error: ld returned 1 exit status
```

If we include Yaml.cpp it'll work:
```
g++ -std=c++11 -Imini-yaml main.cpp mini-yaml/yaml/Yaml.cpp
```

**Comment by jimmiebergmann** [comment]
@jiabinruan No, sorry, due to longer compilation time if yaml.hpp is included more than once in your project. It would be possible to add #define guards for the implementation, but it leads to more work for the user, instead of just adding yaml.cpp to your VS project/makefile once.

@paleozogt 's comment is [discussed here](https://github.com/nothings/single_file_libs/issues/156#issuecomment-496637767).
